name = "organiser-backend"
main = "src/index.ts"
compatibility_date = "2024-10-05"
compatibility_flags = ["nodejs_compat"]

[vars]
MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "organiser-backend"
database_id = "9c04c492-089e-4a74-8634-dba259eba17b"
migrations_dir = "drizzle"

# [ai]
# binding = "AI"

# [observability]
# enabled = true
# head_sampling_rate = 1
